import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const payroll_receipt_tables: KirletTableDecl[] = [
  {
    name: "payroll_receipt",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "payroll_period", type: "text" },
      { name: "employee", type: "text" },
      { name: "snapshot", type: "text" },
      { name: "num_dias_pagados", type: "real" },
      { name: "estado", type: "text" },
      { name: "lineas", type: "json" },
      { name: "total_percepciones", type: "real" },
      { name: "total_deducciones", type: "real" },
      { name: "total_otros_pagos", type: "real" },
      { name: "neto", type: "real" },
      { name: "subsidio_causado", type: "real" },
      { name: "calc_errors", type: "json" },
      { name: "cfdi_document_id", type: "text" },
      { name: "uuid_fiscal", type: "text" },
      { name: "idempotency_key", type: "text" },
      { name: "payload_cfdi", type: "json" },
      { name: "nombre", type: "text" },
      { name: "rfc", type: "text" },
      { name: "curp", type: "text" },
      { name: "nss", type: "text" },
      { name: "num_empleado", type: "text" },
      { name: "salario_diario", type: "real" },
      { name: "sdi", type: "real" },
      { name: "tipo_contrato", type: "text" },
      { name: "tipo_regimen", type: "text" },
      { name: "periodicidad_pago", type: "text" },
      { name: "clave_ent_fed", type: "text" },
      { name: "tipo_sat", type: "text" },
      { name: "clave", type: "text" },
      { name: "concepto", type: "text" },
      { name: "importe_gravado", type: "real" },
      { name: "importe_exento", type: "real" },
      { name: "importe", type: "real" },
    ],
    indexes: [
      { name: "idx_payroll_receipt_name", columns: ["name"] },
      { name: "idx_payroll_receipt_active", columns: ["is_active"] },
    ],
  },
];
