import {
  build_feature_shell_page,
  type KirletPageDecl,
} from "@opus-perpetuus/imperium-core-kit";

const API = "api://m/subject-rh";

export const payroll_receipt_pages: KirletPageDecl[] = [
  {
    id: "rh.payroll-receipt",
    path: "payroll-receipt",
    permission: "subject.rh.payroll-receipt.read",
    build: () =>
      build_feature_shell_page({
        id: "rh.payroll-receipt",
        owner: "subject-rh",
        title: "Recibos de nómina",
        props: {
          basePath: "payroll-receipt",
          idKey: "id",
          nameKey: "name",
          view: {
            title: "Recibos de nómina",
            subtitle: "Submenú de rh",
            pluralLabel: "recibos de nómina",
            singularLabel: "recibos de nómina",
            emptyTitle: "Sin registros",
            emptyDescription: "Migra desde Mongo o crea el primero",
          },
          data: {
            list: `${API}/payroll-receipt`,
            record: `${API}/payroll-receipt/:id`,
            create: { method: "POST", action: `${API}/payroll-receipt` },
            update: { method: "PATCH", action: `${API}/payroll-receipt/:id` },
            delete: { method: "DELETE", action: `${API}/payroll-receipt/:id` },
          },
          table: {
            columns: [
              { key: "name", label: "Nombre", sortable: true, priority: 1 },
              { key: "is_active", label: "Activo", sortable: true, priority: 2 },
              { key: "ref", label: "Ref", sortable: true, priority: 3 },
              { key: "payroll_period", label: "payroll period", sortable: true, priority: 3 },
              { key: "employee", label: "employee", sortable: true, priority: 3 },
              { key: "snapshot", label: "snapshot", sortable: true, priority: 3 },
              { key: "num_dias_pagados", label: "num dias pagados", sortable: true, priority: 3 },
              { key: "estado", label: "estado", sortable: true, priority: 3 },
              { key: "lineas", label: "lineas", sortable: true, priority: 3 },
            ],
            fillHeight: true,
            serverQuery: true,
          },
          form: {
            fields: [
              { name: "name", component: "input-text", label: "Nombre", required: true },
              { name: "description", component: "input-textarea", label: "Descripción" },
              { name: "ref", component: "input-text", label: "Referencia (_ref)" },
              { name: "payroll_period", component: "input-datalist", label: "payroll period", optionsSource: "api://m/subject-rh/payroll-period?as=options&limite=1000" },
              { name: "employee", component: "input-datalist", label: "employee", optionsSource: "api://m/subject-rh/employee?as=options&limite=1000" },
              { name: "snapshot", component: "input-text", label: "snapshot" },
              { name: "num_dias_pagados", component: "input-number", label: "num dias pagados" },
              {
                name: "estado",
                component: "input-menu",
                label: "estado",
                options: [
                  { value: "draft", label: "Borrador" },
                  { value: "calculated", label: "Calculado" },
                  { value: "ready_to_stamp", label: "Listo para timbrar" },
                  { value: "stamping", label: "Timbrando" },
                  { value: "stamped", label: "Timbrado" },
                  { value: "error", label: "Error" },
                ],
              },
              { name: "lineas", component: "input-json", label: "lineas" },
              { name: "total_percepciones", component: "input-money", label: "total percepciones" },
              { name: "total_deducciones", component: "input-money", label: "total deducciones" },
              { name: "total_otros_pagos", component: "input-money", label: "total otros pagos" },
              { name: "neto", component: "input-money", label: "neto" },
              { name: "subsidio_causado", component: "input-money", label: "subsidio causado" },
              { name: "calc_errors", component: "input-json", label: "calc errors" },
              { name: "cfdi_document_id", component: "input-text", label: "cfdi document id" },
              { name: "uuid_fiscal", component: "input-text", label: "uuid fiscal" },
              { name: "idempotency_key", component: "input-text", label: "idempotency key" },
              { name: "payload_cfdi", component: "input-json", label: "payload cfdi" },
              { name: "nombre", component: "input-text", label: "nombre" },
              { name: "rfc", component: "input-text", label: "rfc" },
              { name: "curp", component: "input-mask", label: "curp", mask: "SSSS000000SSSSSSA0" },
              { name: "nss", component: "input-mask", label: "nss", mask: "00000000000" },
              { name: "num_empleado", component: "input-text", label: "num empleado" },
              { name: "salario_diario", component: "input-money", label: "salario diario" },
              { name: "sdi", component: "input-money", label: "sdi" },
              { name: "tipo_contrato", component: "input-text", label: "tipo contrato" },
              { name: "tipo_regimen", component: "input-text", label: "tipo regimen" },
              { name: "periodicidad_pago", component: "input-text", label: "periodicidad pago" },
              { name: "clave_ent_fed", component: "input-text", label: "clave ent fed" },
              { name: "tipo_sat", component: "input-text", label: "tipo sat" },
              { name: "clave", component: "input-text", label: "clave" },
              { name: "concepto", component: "input-text", label: "concepto" },
              { name: "importe_gravado", component: "input-money", label: "importe gravado" },
              { name: "importe_exento", component: "input-money", label: "importe exento" },
              { name: "importe", component: "input-money", label: "importe" },
            ],
          },
        },
      }),
  },
];
