import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { payroll_receipt_pages } from "./payroll-receipt.pages.ts";
import { payroll_receipt_tables } from "./payroll-receipt.tables.ts";

export const payroll_receipt_module = define_module({
  resource: "payroll-receipt",
  labels: {
    singular: "Recibos de nómina",
    plural: "Recibos de nómina",
    read: "Ver Recibos de nómina",
    write: "Editar Recibos de nómina",
  },
  routes: define_crud({
    resource: "payroll-receipt",
    table: "payroll_receipt",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "payroll-",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      payroll_period: { type: "string", search: true },
      employee: { type: "string", search: true },
      snapshot: { type: "string", search: true },
      num_dias_pagados: { type: "number" },
      estado: { type: "string", search: true },
      lineas: { type: "json" },
      total_percepciones: { type: "number" },
      total_deducciones: { type: "number" },
      total_otros_pagos: { type: "number" },
      neto: { type: "number" },
      subsidio_causado: { type: "number" },
      calc_errors: { type: "json" },
      cfdi_document_id: { type: "string", search: true },
      uuid_fiscal: { type: "string", search: true },
      idempotency_key: { type: "string", search: true },
      payload_cfdi: { type: "json" },
      nombre: { type: "string", search: true },
      rfc: { type: "string", search: true },
      curp: { type: "string", search: true },
      nss: { type: "string", search: true },
      num_empleado: { type: "string", search: true },
      salario_diario: { type: "number" },
      sdi: { type: "number" },
      tipo_contrato: { type: "string", search: true },
      tipo_regimen: { type: "string", search: true },
      periodicidad_pago: { type: "string", search: true },
      clave_ent_fed: { type: "string", search: true },
      tipo_sat: { type: "string", search: true },
      clave: { type: "string", search: true },
      concepto: { type: "string", search: true },
      importe_gravado: { type: "number" },
      importe_exento: { type: "number" },
      importe: { type: "number" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: payroll_receipt_tables,
  pages: payroll_receipt_pages,
  menu: [],
});
