import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { employee_pages } from "./employee.pages.ts";
import { employee_tables } from "./employee.tables.ts";

export const employee_module = define_module({
  resource: "employee",
  labels: {
    singular: "Empleados",
    plural: "Empleados",
    read: "Ver Empleados",
    write: "Editar Empleados",
  },
  routes: define_crud({
    resource: "employee",
    table: "employee",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "employee",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      image: { type: "string", search: true },
      department: { type: "string", search: true },
      branch_office: { type: "string", search: true },
      state_id: { type: "string", search: true },
      municipality: { type: "string", search: true },
      boroughs: { type: "string", search: true },
      street: { type: "string", search: true },
      exterior_number: { type: "string", search: true },
      interior_number: { type: "string", search: true },
      postal_code: { type: "string", search: true },
      country: { type: "string", search: true },
      puesto: { type: "string", search: true },
      rfc: { type: "string", search: true },
      curp: { type: "string", search: true },
      nss: { type: "string", search: true },
      num_empleado: { type: "string", search: true },
      fecha_nacimiento: { type: "string", search: true },
      sexo: { type: "string", search: true },
      fecha_ingreso: { type: "string", search: true },
      fecha_baja: { type: "string", search: true },
      tipo_contrato: { type: "string", search: true },
      tipo_regimen: { type: "string", search: true },
      tipo_jornada: { type: "string", search: true },
      riesgo_puesto: { type: "string", search: true },
      periodicidad_pago: { type: "string", search: true },
      clave_ent_fed: { type: "string", search: true },
      salario_diario: { type: "string", search: true },
      sdi: { type: "string", search: true },
      banco: { type: "string", search: true },
      cuenta: { type: "string", search: true },
      clabe: { type: "string", search: true },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: employee_tables,
  pages: employee_pages,
  menu: [],
});
