import {
  build_feature_shell_page,
  type KirletPageDecl,
} from "@opus-perpetuus/imperium-core-kit";

const API = "api://m/subject-rh";

export const employee_pages: KirletPageDecl[] = [
  {
    id: "rh.employee",
    path: "employee",
    permission: "subject.rh.employee.read",
    build: () =>
      build_feature_shell_page({
        id: "rh.employee",
        owner: "subject-rh",
        title: "Empleados",
        props: {
          basePath: "employee",
          idKey: "id",
          nameKey: "name",
          view: {
            title: "Empleados",
            subtitle: "Submenú de rh",
            pluralLabel: "empleados",
            singularLabel: "empleados",
            emptyTitle: "Sin registros",
            emptyDescription: "Migra desde Mongo o crea el primero",
          },
          data: {
            list: `${API}/employee`,
            record: `${API}/employee/:id`,
            create: { method: "POST", action: `${API}/employee` },
            update: { method: "PATCH", action: `${API}/employee/:id` },
            delete: { method: "DELETE", action: `${API}/employee/:id` },
          },
          table: {
            columns: [
              { key: "name", label: "Nombre", sortable: true, priority: 1 },
              { key: "is_active", label: "Activo", sortable: true, priority: 2 },
              { key: "ref", label: "Ref", sortable: true, priority: 3 },
              { key: "image", label: "image", sortable: true, priority: 3 },
              { key: "department", label: "department", sortable: true, priority: 3 },
              { key: "branch_office", label: "branch office", sortable: true, priority: 3 },
              { key: "state_id", label: "state id", sortable: true, priority: 3 },
              { key: "municipality", label: "municipality", sortable: true, priority: 3 },
              { key: "boroughs", label: "boroughs", sortable: true, priority: 3 },
            ],
            fillHeight: true,
            serverQuery: true,
          },
          form: {
            fields: [
              { name: "name", component: "input-text", label: "Nombre", required: true },
              { name: "description", component: "input-textarea", label: "Descripción" },
              { name: "ref", component: "input-text", label: "Referencia (_ref)" },
              { name: "image", component: "input-image", label: "image" },
              { name: "department", component: "input-datalist", label: "department", optionsSource: "api://m/subject-rh/departments?as=options&limite=1000" },
              { name: "branch_office", component: "input-datalist", label: "branch office", optionsSource: "api://m/subject-configuracion/branchoffice?as=options&limite=1000" },
              { name: "state_id", component: "input-datalist", label: "state id", optionsSource: "api://m/subject-control-municipal/states?as=options&limite=1000" },
              { name: "municipality", component: "input-datalist", label: "municipality", optionsSource: "api://m/subject-control-municipal/municipality?as=options&limite=1000" },
              { name: "boroughs", component: "input-datalist", label: "boroughs", optionsSource: "api://m/subject-control-municipal/boroughs?as=options&limite=1000" },
              { name: "street", component: "input-text", label: "street" },
              { name: "exterior_number", component: "input-text", label: "exterior number" },
              { name: "interior_number", component: "input-text", label: "interior number" },
              { name: "postal_code", component: "input-mask", label: "postal code", mask: "00000" },
              { name: "country", component: "input-text", label: "country" },
              { name: "puesto", component: "input-text", label: "puesto" },
              { name: "rfc", component: "input-text", label: "rfc" },
              { name: "curp", component: "input-mask", label: "curp", mask: "SSSS000000SSSSSSA0" },
              { name: "nss", component: "input-mask", label: "nss", mask: "00000000000" },
              { name: "num_empleado", component: "input-text", label: "num empleado" },
              { name: "fecha_nacimiento", component: "input-date", label: "fecha nacimiento" },
              {
                name: "sexo",
                component: "input-menu",
                label: "sexo",
                options: [
                  { value: "H", label: "Hombre (H)" },
                  { value: "M", label: "Mujer (M)" },
                ],
              },
              { name: "fecha_ingreso", component: "input-date", label: "fecha ingreso" },
              { name: "fecha_baja", component: "input-date", label: "fecha baja" },
              {
                name: "tipo_contrato",
                component: "input-menu",
                label: "tipo contrato",
                options: [
                  { value: "01", label: "01 — Contrato de trabajo por tiempo indeterminado" },
                  { value: "02", label: "02 — Por obra determinada" },
                  { value: "03", label: "03 — Por tiempo determinado" },
                  { value: "04", label: "04 — Por temporada" },
                  { value: "05", label: "05 — Sujeto a prueba" },
                  { value: "06", label: "06 — Con capacitación inicial" },
                  { value: "07", label: "07 — Por pago de hora laborada" },
                  { value: "08", label: "08 — Labor que no requiere labor continua" },
                  { value: "09", label: "09 — Comisión laboral" },
                  { value: "10", label: "10 — Modalidad de teletrabajo" },
                  { value: "99", label: "99 — Otro contrato" },
                ],
              },
              {
                name: "tipo_regimen",
                component: "input-datalist",
                label: "tipo regimen",
                options: [
                  { value: "02", label: "02 — Sueldos (incluye ingresos asimilados a salarios)" },
                  { value: "03", label: "03 — Jubilados" },
                  { value: "04", label: "04 — Pensionados" },
                  { value: "05", label: "05 — Asimilados miembros sociedades cooperativas producción" },
                  { value: "06", label: "06 — Asimilados a salarios socios e integrantes" },
                  { value: "07", label: "07 — Asimilados a salarios miembros consejos" },
                  { value: "08", label: "08 — Asimilados a salarios comisionistas" },
                  { value: "09", label: "09 — Asimilados a salarios honorarios" },
                  { value: "10", label: "10 — Asimilados a salarios acciones" },
                  { value: "11", label: "11 — Asimilados a salarios otros" },
                  { value: "12", label: "12 — Jubilados o Pensionados" },
                  { value: "13", label: "13 — Indemnización o Separación" },
                  { value: "99", label: "99 — Otro Régimen" },
                ],
              },
              {
                name: "tipo_jornada",
                component: "input-menu",
                label: "tipo jornada",
                options: [
                  { value: "01", label: "01 — Diurna" },
                  { value: "02", label: "02 — Nocturna" },
                  { value: "03", label: "03 — Mixta" },
                  { value: "04", label: "04 — Por hora" },
                  { value: "05", label: "05 — Reducida" },
                  { value: "06", label: "06 — Continuada" },
                  { value: "07", label: "07 — Partida" },
                  { value: "08", label: "08 — Por turnos" },
                  { value: "99", label: "99 — Otra Jornada" },
                ],
              },
              {
                name: "riesgo_puesto",
                component: "input-menu",
                label: "riesgo puesto",
                options: [
                  { value: "1", label: "1 — Clase I" },
                  { value: "2", label: "2 — Clase II" },
                  { value: "3", label: "3 — Clase III" },
                  { value: "4", label: "4 — Clase IV" },
                  { value: "5", label: "5 — Clase V" },
                  { value: "99", label: "99 — No aplica" },
                ],
              },
              {
                name: "periodicidad_pago",
                component: "input-menu",
                label: "periodicidad pago",
                options: [
                  { value: "01", label: "01 — Diario" },
                  { value: "02", label: "02 — Semanal" },
                  { value: "03", label: "03 — Catorcenal" },
                  { value: "04", label: "04 — Quincenal" },
                  { value: "05", label: "05 — Mensual" },
                  { value: "06", label: "06 — Bimestral" },
                  { value: "07", label: "07 — Unidad obra" },
                  { value: "08", label: "08 — Comisión" },
                  { value: "09", label: "09 — Precio alzado" },
                  { value: "10", label: "10 — Decenal" },
                  { value: "99", label: "99 — Otra Periodicidad" },
                ],
              },
              {
                name: "clave_ent_fed",
                component: "input-datalist",
                label: "clave ent fed",
                options: [
                  { value: "AGU", label: "AGU — Aguascalientes" },
                  { value: "BCN", label: "BCN — Baja California" },
                  { value: "BCS", label: "BCS — Baja California Sur" },
                  { value: "CAM", label: "CAM — Campeche" },
                  { value: "CHP", label: "CHP — Chiapas" },
                  { value: "CHH", label: "CHH — Chihuahua" },
                  { value: "CMX", label: "CMX — Ciudad de México" },
                  { value: "COA", label: "COA — Coahuila" },
                  { value: "COL", label: "COL — Colima" },
                  { value: "DUR", label: "DUR — Durango" },
                  { value: "GUA", label: "GUA — Guanajuato" },
                  { value: "GRO", label: "GRO — Guerrero" },
                  { value: "HID", label: "HID — Hidalgo" },
                  { value: "JAL", label: "JAL — Jalisco" },
                  { value: "MEX", label: "MEX — Estado de México" },
                  { value: "MIC", label: "MIC — Michoacán" },
                  { value: "MOR", label: "MOR — Morelos" },
                  { value: "NAY", label: "NAY — Nayarit" },
                  { value: "NLE", label: "NLE — Nuevo León" },
                  { value: "OAX", label: "OAX — Oaxaca" },
                  { value: "PUE", label: "PUE — Puebla" },
                  { value: "QUE", label: "QUE — Querétaro" },
                  { value: "ROO", label: "ROO — Quintana Roo" },
                  { value: "SLP", label: "SLP — San Luis Potosí" },
                  { value: "SIN", label: "SIN — Sinaloa" },
                  { value: "SON", label: "SON — Sonora" },
                  { value: "TAB", label: "TAB — Tabasco" },
                  { value: "TAM", label: "TAM — Tamaulipas" },
                  { value: "TLA", label: "TLA — Tlaxcala" },
                  { value: "VER", label: "VER — Veracruz" },
                  { value: "YUC", label: "YUC — Yucatán" },
                  { value: "ZAC", label: "ZAC — Zacatecas" },
                ],
              },
              { name: "salario_diario", component: "input-money", label: "salario diario" },
              { name: "sdi", component: "input-money", label: "sdi" },
              { name: "banco", component: "input-text", label: "banco" },
              { name: "cuenta", component: "input-text", label: "cuenta" },
              { name: "clabe", component: "input-mask", label: "clabe", mask: "000000000000000000" },
            ],
          },
        },
      }),
  },
];
