import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const employee_tables: KirletTableDecl[] = [
  {
    name: "employee",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "image", type: "text" },
      { name: "department", type: "text" },
      { name: "branch_office", type: "text" },
      { name: "state_id", type: "text" },
      { name: "municipality", type: "text" },
      { name: "boroughs", type: "text" },
      { name: "street", type: "text" },
      { name: "exterior_number", type: "text" },
      { name: "interior_number", type: "text" },
      { name: "postal_code", type: "text" },
      { name: "country", type: "text" },
      { name: "puesto", type: "text" },
      { name: "rfc", type: "text" },
      { name: "curp", type: "text" },
      { name: "nss", type: "text" },
      { name: "num_empleado", type: "text" },
      { name: "fecha_nacimiento", type: "text" },
      { name: "sexo", type: "text" },
      { name: "fecha_ingreso", type: "text" },
      { name: "fecha_baja", type: "text" },
      { name: "tipo_contrato", type: "text" },
      { name: "tipo_regimen", type: "text" },
      { name: "tipo_jornada", type: "text" },
      { name: "riesgo_puesto", type: "text" },
      { name: "periodicidad_pago", type: "text" },
      { name: "clave_ent_fed", type: "text" },
      { name: "salario_diario", type: "text" },
      { name: "sdi", type: "text" },
      { name: "banco", type: "text" },
      { name: "cuenta", type: "text" },
      { name: "clabe", type: "text" },
    ],
    indexes: [
      { name: "idx_employee_name", columns: ["name"] },
      { name: "idx_employee_active", columns: ["is_active"] },
    ],
  },
];
